name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  Check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Check formatting
        run: cargo fmt --check

      - name: Run tests
        run: cargo test --verbose
